version: '3.8'
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=iam-db
    ports:
      - '5436:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - iam
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'

networks:
  iam: {}

volumes:
  pgdata: {}
  logs: {}
  log_history: {}
  config: {}
